config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get'home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :destroy, :index, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'users#followings', as: 'followings'
    get 'followers' => 'users#followers', as: 'followers'
  end
  get '/search', to: 'searchs#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comment, dependent: :destroy
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end

    validates :title, presence: true
    validates :body, length: { in: 1..200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy
  
  # フォローをした、されたの関係↓
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う↓
  has_many :followings, through: :relationships, source: :followed # 自分がフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower # 自分をフォローしている人
  
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end
  
  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    redirect_to book_path(@book.id), flash: {success: "You have created book successfully."}
   else
    @books = Book.all
    @user = current_user
    render :index
   end

  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user

  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = User.find_by(id: @books.user_id)
  end

  def edit
    @book = Book.new
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), flash: {notice: "You have updated book successfully."}
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to book_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user.id), flash: {notice: "You have updated user successfully."}
    else
      render :edit
    end
  end

  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              　<%= attachment_image_tag book.user, :profile_image,:saiz, "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>

app/views/books/_list.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

      <h2>User info</h2>
      <table class="table">

        <tbody>
          <tr><%= attachment_image_tag user, :profile_image,:saiz, "63x63", format: 'jpeg', fallback: "no_image.jpg" %></tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>

          <tr>
            <th>follows</th>
            <th>
              <%= link_to user_followings_path(user.id) do %>
              <%= user.followings.count %>
              <% end %>
            <!--フォローviewができたらlink_to-->
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to user_followers_path(user.id) do %>
                <%= user.followers.count %>
              <% end %>
              <!--フォロワーviewができたらlink_to-->
            </th>
          </tr>

        </tbody>
      </table>
      <div class="row">
        <% unless current_user == user %>
        <% if current_user.following?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
        <% end %>
      </div>

      <div class="row">
        <%= link_to edit_user_path(user.id) do %>
          <i class="fas fa-user-cog btn btn-outline-secondary btn-block"></i>
        <% end %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model:book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>

app/views/books/_users.html.erb
<% users.each do |user| %>
  <%= link_to user_path(user) do %>
    <%= user.name %><br>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
            <label for="book_opinions">Optinion</label>
            <%= f.text_field :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
            <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
        <% end %>
        <a><%= link_to "Show", book_path(@book.id) %></a> |
        <a><%= link_to "Back", books_path %></a>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<%= render'books/list',{book: @book, user: @user} %>
    <div class="col-md-8 offset-md-1">
      <%= render 'searchs/form' %>
      <h2>Books</h2>
      <%= render 'books/index',{books:@books, user:@user} %>
    </div>

app/views/books/show.html.erb
<%= render'books/list',{book:@book, user:@user} %>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
         <td>
           <%= link_to user_path(@user.id) do %>
           <%= attachment_image_tag @user, :profile_image,:saiz, "40x40", format: 'jpeg', fallback: "no_image.jpg" %><br>
           <%= @user.name %>
           <% end %>
         </td>
         <td>
           <%= link_to book_path(@books.id) do %>
           <%= @books.title %>
           <% end %>
         </td>
         <td>
           <%= @books.body %>
         </td>

         <% if @books.user == current_user %>
         <td>
           <%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %>
         </td>
         <td>
           <%= link_to "Destroy", book_path(@books), method: :delete, class: "btn btn-sm btn-danger" %>
         </td>
         <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/homes/about.html.erb
<h1>
  Welcome <div class="social"><i class="fas fa-book"></i></div><strong>Bookers</strong>!
</h1>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searchs/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searchs/search.html.erb
<%= render 'searchs/form' %>
<% if @model == 'user' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% else @model == 'books' %>
  <h3>Books search for "<%= @content %>"</h3>
    <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% if users.exists? %>
      <!--モデル名.exists?(条件)-->
      <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image,:saiz, "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>

        <td>
          <% unless current_user == user %>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
          <% end %>
        </td>

      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のerrorが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name", class: "form-control name" %>
      </div>
      <div class="form-group">
        <label for="image">Image</label>
        <%= f.attachment_field:profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <label for="inputImage">Introduction</label>
        <%= f.text_field :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= attachment_image_tag user, :profile_image,:saiz, "63x63", format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/followings.html.erb
<h1>Follower Users</h1>
<% if @users.exists? %>
  <% @users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= attachment_image_tag user, :profile_image,:saiz, "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<%= render'books/list',{book:@book, user:@user} %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <%= render'users/index',{users:@users} %>
</div>
  

app/views/users/show.html.erb
<%= render'books/list',{book:@book, user:@user} %>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag @user, :profile_image,:saiz, "40x40", format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>